//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Hotkeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Hotkeys defaultInstance = ((Hotkeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Hotkeys())));
        
        public static Hotkeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public global::System.Windows.Forms.Keys AGL_Altitude {
            get {
                return ((global::System.Windows.Forms.Keys)(this["AGL_Altitude"]));
            }
            set {
                this["AGL_Altitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem6")]
        public global::System.Windows.Forms.Keys Command_Key {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Command_Key"]));
            }
            set {
                this["Command_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys ASL_Altitude {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ASL_Altitude"]));
            }
            set {
                this["ASL_Altitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public global::System.Windows.Forms.Keys Aircraft_Heading {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Aircraft_Heading"]));
            }
            set {
                this["Aircraft_Heading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys Indicated_Airspeed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Indicated_Airspeed"]));
            }
            set {
                this["Indicated_Airspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public global::System.Windows.Forms.Keys True_Airspeed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["True_Airspeed"]));
            }
            set {
                this["True_Airspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public global::System.Windows.Forms.Keys Mach_Speed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Mach_Speed"]));
            }
            set {
                this["Mach_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public global::System.Windows.Forms.Keys Vertical_Speed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Vertical_Speed"]));
            }
            set {
                this["Vertical_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O")]
        public global::System.Windows.Forms.Keys Outside_Temperature {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Outside_Temperature"]));
            }
            set {
                this["Outside_Temperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+T")]
        public global::System.Windows.Forms.Keys Toggle_Trim_Announcement {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Toggle_Trim_Announcement"]));
            }
            set {
                this["Toggle_Trim_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+R")]
        public global::System.Windows.Forms.Keys Mute_Simconnect_Messages {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Mute_Simconnect_Messages"]));
            }
            set {
                this["Mute_Simconnect_Messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public global::System.Windows.Forms.Keys Nearest_City {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Nearest_City"]));
            }
            set {
                this["Nearest_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys Next_Waypoint {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Next_Waypoint"]));
            }
            set {
                this["Next_Waypoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys Destination_Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Destination_Info"]));
            }
            set {
                this["Destination_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OemOpenBrackets")]
        public global::System.Windows.Forms.Keys Attitude_Mode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Attitude_Mode"]));
            }
            set {
                this["Attitude_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+M")]
        public global::System.Windows.Forms.Keys Speak_Attitude {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Speak_Attitude"]));
            }
            set {
                this["Speak_Attitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+A")]
        public global::System.Windows.Forms.Keys Toggle_Autopilot_Announcement {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Toggle_Autopilot_Announcement"]));
            }
            set {
                this["Toggle_Autopilot_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+G")]
        public global::System.Windows.Forms.Keys Toggle_GPWS_Announcement {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Toggle_GPWS_Announcement"]));
            }
            set {
                this["Toggle_GPWS_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+I")]
        public global::System.Windows.Forms.Keys Toggle_ILS_Announcement {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Toggle_ILS_Announcement"]));
            }
            set {
                this["Toggle_ILS_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F")]
        public global::System.Windows.Forms.Keys Toggle_Flaps_Announcement {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Toggle_Flaps_Announcement"]));
            }
            set {
                this["Toggle_Flaps_Announcement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public global::System.Windows.Forms.Keys Wind_Information {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Wind_Information"]));
            }
            set {
                this["Wind_Information"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+H")]
        public global::System.Windows.Forms.Keys Runway_Guidance_Mode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Runway_Guidance_Mode"]));
            }
            set {
                this["Runway_Guidance_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public global::System.Windows.Forms.Keys Fuel_Report {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Report"]));
            }
            set {
                this["Fuel_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public global::System.Windows.Forms.Keys Fuel_Flow {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Flow"]));
            }
            set {
                this["Fuel_Flow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public global::System.Windows.Forms.Keys Fuel_Tank_1 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_1"]));
            }
            set {
                this["Fuel_Tank_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public global::System.Windows.Forms.Keys Fuel_Tank_2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_2"]));
            }
            set {
                this["Fuel_Tank_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public global::System.Windows.Forms.Keys Fuel_Tank_3 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_3"]));
            }
            set {
                this["Fuel_Tank_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public global::System.Windows.Forms.Keys Fuel_Tank_4 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_4"]));
            }
            set {
                this["Fuel_Tank_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public global::System.Windows.Forms.Keys Fuel_Tank_5 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_5"]));
            }
            set {
                this["Fuel_Tank_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public global::System.Windows.Forms.Keys Fuel_Tank_6 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_6"]));
            }
            set {
                this["Fuel_Tank_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public global::System.Windows.Forms.Keys Fuel_Tank_7 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_7"]));
            }
            set {
                this["Fuel_Tank_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public global::System.Windows.Forms.Keys Fuel_Tank_8 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_8"]));
            }
            set {
                this["Fuel_Tank_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public global::System.Windows.Forms.Keys Fuel_Tank_9 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_9"]));
            }
            set {
                this["Fuel_Tank_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Forms.Keys Fuel_Tank_10 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Fuel_Tank_10"]));
            }
            set {
                this["Fuel_Tank_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public global::System.Windows.Forms.Keys Nearby_Airborn_Aircraft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Nearby_Airborn_Aircraft"]));
            }
            set {
                this["Nearby_Airborn_Aircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+P")]
        public global::System.Windows.Forms.Keys Nearby_Ground_Aircraft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Nearby_Ground_Aircraft"]));
            }
            set {
                this["Nearby_Ground_Aircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+1")]
        public global::System.Windows.Forms.Keys Engine_1_Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_1_Info"]));
            }
            set {
                this["Engine_1_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+2")]
        public global::System.Windows.Forms.Keys Engine_2_Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_2_Info"]));
            }
            set {
                this["Engine_2_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+3")]
        public global::System.Windows.Forms.Keys Engine_3_Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_3_Info"]));
            }
            set {
                this["Engine_3_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+4")]
        public global::System.Windows.Forms.Keys Engine_4_Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_4_Info"]));
            }
            set {
                this["Engine_4_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+W")]
        public global::System.Windows.Forms.Keys Weight_Report {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Weight_Report"]));
            }
            set {
                this["Weight_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public global::System.Windows.Forms.Keys Repeat_Last_Simconnect_Message {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Repeat_Last_Simconnect_Message"]));
            }
            set {
                this["Repeat_Last_Simconnect_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::System.Windows.Forms.Keys Read_Simulation_Rate {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Read_Simulation_Rate"]));
            }
            set {
                this["Read_Simulation_Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public global::System.Windows.Forms.Keys Ground_Speed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Ground_Speed"]));
            }
            set {
                this["Ground_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+1")]
        public global::System.Windows.Forms.Keys Engine_1_Throttle {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_1_Throttle"]));
            }
            set {
                this["Engine_1_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+2")]
        public global::System.Windows.Forms.Keys Engine_2_Throttle {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_2_Throttle"]));
            }
            set {
                this["Engine_2_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+3")]
        public global::System.Windows.Forms.Keys Engine_3_Throttle {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_3_Throttle"]));
            }
            set {
                this["Engine_3_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+4")]
        public global::System.Windows.Forms.Keys Engine_4_Throttle {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine_4_Throttle"]));
            }
            set {
                this["Engine_4_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+C")]
        public global::System.Windows.Forms.Keys Current_Location {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Current_Location"]));
            }
            set {
                this["Current_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public global::System.Windows.Forms.Keys Disable_Command_Key {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Disable_Command_Key"]));
            }
            set {
                this["Disable_Command_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+B")]
        public global::System.Windows.Forms.Keys Toggle_Braille_output {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Toggle_Braille_output"]));
            }
            set {
                this["Toggle_Braille_output"] = value;
            }
        }
    }
}
