//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Hotkeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Hotkeys defaultInstance = ((Hotkeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Hotkeys())));
        
        public static Hotkeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public global::System.Windows.Forms.Keys agl {
            get {
                return ((global::System.Windows.Forms.Keys)(this["agl"]));
            }
            set {
                this["agl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem6")]
        public global::System.Windows.Forms.Keys command {
            get {
                return ((global::System.Windows.Forms.Keys)(this["command"]));
            }
            set {
                this["command"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys asl {
            get {
                return ((global::System.Windows.Forms.Keys)(this["asl"]));
            }
            set {
                this["asl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public global::System.Windows.Forms.Keys heading {
            get {
                return ((global::System.Windows.Forms.Keys)(this["heading"]));
            }
            set {
                this["heading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys IndicatedAirspeed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["IndicatedAirspeed"]));
            }
            set {
                this["IndicatedAirspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public global::System.Windows.Forms.Keys TrueAirspeed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["TrueAirspeed"]));
            }
            set {
                this["TrueAirspeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public global::System.Windows.Forms.Keys MachSpeed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MachSpeed"]));
            }
            set {
                this["MachSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public global::System.Windows.Forms.Keys VerticalSpeed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["VerticalSpeed"]));
            }
            set {
                this["VerticalSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O")]
        public global::System.Windows.Forms.Keys AirTemperature {
            get {
                return ((global::System.Windows.Forms.Keys)(this["AirTemperature"]));
            }
            set {
                this["AirTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+T")]
        public global::System.Windows.Forms.Keys ToggleTrim {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleTrim"]));
            }
            set {
                this["ToggleTrim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+R")]
        public global::System.Windows.Forms.Keys MuteSimconnect {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MuteSimconnect"]));
            }
            set {
                this["MuteSimconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public global::System.Windows.Forms.Keys FlightFollowing {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FlightFollowing"]));
            }
            set {
                this["FlightFollowing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys NextWaypoint {
            get {
                return ((global::System.Windows.Forms.Keys)(this["NextWaypoint"]));
            }
            set {
                this["NextWaypoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys DestinationInfo {
            get {
                return ((global::System.Windows.Forms.Keys)(this["DestinationInfo"]));
            }
            set {
                this["DestinationInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OemOpenBrackets")]
        public global::System.Windows.Forms.Keys AttitudeMode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["AttitudeMode"]));
            }
            set {
                this["AttitudeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+M")]
        public global::System.Windows.Forms.Keys SpeakAttitude {
            get {
                return ((global::System.Windows.Forms.Keys)(this["SpeakAttitude"]));
            }
            set {
                this["SpeakAttitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+A")]
        public global::System.Windows.Forms.Keys SpeakAutopilot {
            get {
                return ((global::System.Windows.Forms.Keys)(this["SpeakAutopilot"]));
            }
            set {
                this["SpeakAutopilot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+G")]
        public global::System.Windows.Forms.Keys ToggleGPWS {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleGPWS"]));
            }
            set {
                this["ToggleGPWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+I")]
        public global::System.Windows.Forms.Keys ToggleILS {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleILS"]));
            }
            set {
                this["ToggleILS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F")]
        public global::System.Windows.Forms.Keys ToggleFlapsAnnouncement {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleFlapsAnnouncement"]));
            }
            set {
                this["ToggleFlapsAnnouncement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public global::System.Windows.Forms.Keys ReadWind {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ReadWind"]));
            }
            set {
                this["ReadWind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+H")]
        public global::System.Windows.Forms.Keys RunwayGuidance {
            get {
                return ((global::System.Windows.Forms.Keys)(this["RunwayGuidance"]));
            }
            set {
                this["RunwayGuidance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public global::System.Windows.Forms.Keys FuelReport {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelReport"]));
            }
            set {
                this["FuelReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public global::System.Windows.Forms.Keys FuelFlow {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelFlow"]));
            }
            set {
                this["FuelFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public global::System.Windows.Forms.Keys FuelTank1 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank1"]));
            }
            set {
                this["FuelTank1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public global::System.Windows.Forms.Keys FuelTank2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank2"]));
            }
            set {
                this["FuelTank2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public global::System.Windows.Forms.Keys FuelTank3 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank3"]));
            }
            set {
                this["FuelTank3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public global::System.Windows.Forms.Keys FuelTank4 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank4"]));
            }
            set {
                this["FuelTank4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public global::System.Windows.Forms.Keys FuelTank5 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank5"]));
            }
            set {
                this["FuelTank5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public global::System.Windows.Forms.Keys FuelTank6 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank6"]));
            }
            set {
                this["FuelTank6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public global::System.Windows.Forms.Keys FuelTank7 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank7"]));
            }
            set {
                this["FuelTank7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public global::System.Windows.Forms.Keys FuelTank8 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank8"]));
            }
            set {
                this["FuelTank8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public global::System.Windows.Forms.Keys FuelTank9 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank9"]));
            }
            set {
                this["FuelTank9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Forms.Keys FuelTank10 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FuelTank10"]));
            }
            set {
                this["FuelTank10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public global::System.Windows.Forms.Keys NearbyAirborn {
            get {
                return ((global::System.Windows.Forms.Keys)(this["NearbyAirborn"]));
            }
            set {
                this["NearbyAirborn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+P")]
        public global::System.Windows.Forms.Keys NearbyGround {
            get {
                return ((global::System.Windows.Forms.Keys)(this["NearbyGround"]));
            }
            set {
                this["NearbyGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+1")]
        public global::System.Windows.Forms.Keys Engine1Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine1Info"]));
            }
            set {
                this["Engine1Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+2")]
        public global::System.Windows.Forms.Keys Engine2Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine2Info"]));
            }
            set {
                this["Engine2Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+3")]
        public global::System.Windows.Forms.Keys Engine3Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine3Info"]));
            }
            set {
                this["Engine3Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+4")]
        public global::System.Windows.Forms.Keys Engine4Info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Engine4Info"]));
            }
            set {
                this["Engine4Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+W")]
        public global::System.Windows.Forms.Keys WeightReport {
            get {
                return ((global::System.Windows.Forms.Keys)(this["WeightReport"]));
            }
            set {
                this["WeightReport"] = value;
            }
        }
    }
}
